[FEAT] 닉네임 생성 UI 구현
DeveloperAcademy-POSTECH/MacC-Team-Maddori.Apple pull request #14
Opened 2022-10-18 14:44 UTC by dangsal

## 🌁 Background

닉네임 생성 UI 구현입니다. 

## 👩‍💻 Contents

- 닉네임 뷰 라벨 생성
- 텍스트필드 생성
- 텍스트필드 제한 구현
- 키보드 위치에 따라 애니메이션 
- 메인버튼 생성
- 메인버튼 활성화 비활성화
- 텍스트 필드 컴포넌트화 하기

## ✅ Testing

- 11번 브랜치로 이동해 오셔서 보고 가셔요~~!!

## 📱 Screenshot

https://user-images.githubusercontent.com/59243274/196462305-afceacd6-6c0c-4ebb-b0c7-ebe54b02057c.mp4

## 📝 Review Note

한 화면에 대한 pr을 한번에 날리게 됐는데 이것도 하나하나 나눠서 하는게 좋을지 궁금합니다. 
사실 제가 맡은 화면은 내용이 많지 않아서 하나로 해도 되겠다고 판단했지만 막상 UI구현하고 나니 아무래도 없던 파일이 생성되는것이다보니 리뷰가 많네요.

다음 pr 부터는 컴포넌트 하나하나에 pr로 해볼까? 라는 생각인데 어떻게 생각하시는지 의견 주시면 감사하겠습니다

## 📣 Related Issue

- close #11 

## 📬 Reference

2022-10-18 14:45 UTC, dangsal commented on Maddori.Apple/Maddori.Apple/Global/Base/BaseViewController.swift
> +        hideKeyboardWhenTappedAround()
화면 어디를 눌러도 키보드가 내려오는 동작을 하는 함수는 텍스트 필드가 들어가는 모든 뷰에 중복될거 같아서 BaseViewController 에 작성했습니다.

2022-10-18 14:47 UTC, dangsal commented on Maddori.Apple/Maddori.Apple/Global/UIComponent/KigoTextField.swift
> +
텍스트 필드를 컴포넌트 화 하는 과정에서 플레이스 홀더의 텍스트만 변경되면 되겠다? 라고 생각해서 이 당시에는 변수명을 어떻게 할까 하다가 inText라고 했는데 PR을 작성하면서 placeholderText 로 했으면 어땠을까? 라는 생각이 드네요.

바꿀까요?

2022-10-18 14:51 UTC, Guel-git commented on Maddori.Apple/Maddori.Apple/Global/Base/BaseViewController.swift
> +        hideKeyboardWhenTappedAround()
최고의 선생님! 😁

2022-10-18 14:53 UTC, Guel-git commented on Maddori.Apple/Maddori.Apple/Global/UIComponent/KigoTextField.swift
> +        let leftPaddingView = UIView(frame: CGRect(x: 0, y: 0, width: 16, height: 0))
p1;
left padding 18px 인 것 같아요!

2022-10-18 14:54 UTC, Guel-git commented on Maddori.Apple/Maddori.Apple/Screen/Signup/SignupViewController.swift
> +        label.text = "키고에서 사용할 \n닉네임을 입력해주세요"
p5;
TextLiteral 만들어서 하나에 정리하는 건 어떨까요?

2022-10-18 14:58 UTC, Guel-git commented on Maddori.Apple/Maddori.Apple/Screen/Signup/SignupViewController.swift
> +            $0.top.equalTo(titleLabel.snp.bottom).offset(39)
p1;
호야께서 알고 계시지만 확인용으로 커멘트 남깁니다..! 40으로 부탁드려요!

2022-10-18 14:59 UTC, dangsal commented on Maddori.Apple/Maddori.Apple/Screen/Signup/SignupViewController.swift
> +            $0.top.equalTo(view.safeAreaLayoutGuide).inset(SizeLiteral.leadingTrailingPadding)
아 요고는 제가 Size리터럴에 topPadding으로 빼다가 리딩트레일링 패딩을 넣어버렸네요 ㅠㅠ 수정하겠습니다!

2022-10-18 15:01 UTC, dangsal commented on Maddori.Apple/Maddori.Apple/Global/UIComponent/KigoTextField.swift
> +        let leftPaddingView = UIView(frame: CGRect(x: 0, y: 0, width: 16, height: 0))
[0e8f035](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Maddori.Apple/pull/14/commits/0e8f035813d2fab61142f5f60311153c96fde13e) 
수정완료요!!

2022-10-18 15:02 UTC, dangsal commented on Maddori.Apple/Maddori.Apple/Screen/Signup/SignupViewController.swift
> +        label.text = "키고에서 사용할 \n닉네임을 입력해주세요"
요고는 아마 진저가 리뷰 남기는 동안 수정된 사항인거같아요!! 새로고침이 슬쩍 필요할듯해요!!

2022-10-18 15:04 UTC, Guel-git commented on Maddori.Apple/Maddori.Apple/Screen/Signup/SignupViewController.swift
> +    // MARK: - life cycle
p5;
아주아주 사소한 건데 ... 여기 한 칸만 띄워주실 수 있나요....?

2022-10-18 15:07 UTC, dangsal commented on Maddori.Apple/Maddori.Apple/Screen/Signup/SignupViewController.swift
> +    // MARK: - life cycle
[4a6489f](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Maddori.Apple/pull/14/commits/4a6489ffbc03d1c256afac53d61a2465555fad7a)

수정완료!!

2022-10-18 15:07 UTC, dangsal commented on Maddori.Apple/Maddori.Apple/Screen/Signup/SignupViewController.swift
> +        label.font = .body2
[4a6489f](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Maddori.Apple/pull/14/commits/4a6489ffbc03d1c256afac53d61a2465555fad7a)

수정완료!

2022-10-18 15:09 UTC, Guel-git commented on Maddori.Apple/Maddori.Apple/Screen/Signup/SignupViewController.swift
> +                self.doneButton.transform = CGAffineTransform(translationX: 0, y: -keyboardSize.height + 30)
p2;
시뮬레이터 상에서는 키보드 상단에 자동완성 테이블이 있어서 그런건지 지금보다(30) 살짝 크게 띄워 주어야 피그마에서처럼 느낌이 날 것 같은데 호야 생각은 어떠신가요??

2022-10-18 15:10 UTC, Guel-git commented on Maddori.Apple/Maddori.Apple/Screen/Signup/SignupViewController.swift
> +                textField.text = fixedText + " "
p5;
이 부분 코드 한 번만 설명 부탁드려도 될까용? 🧐 궁금합니다!

2022-10-18 16:03 UTC, dangsal commented on Maddori.Apple/Maddori.Apple/Global/UIComponent/KigoTextField.swift
> +
placeholderText로 변경했습니당!

2022-10-18 16:35 UTC, dangsal commented on Maddori.Apple/Maddori.Apple/Screen/Signup/SignupViewController.swift
> +                textField.text = fixedText + " "
이 부분을 사실 굉장히 복잡하게 보이지만 그렇지 않습니다! 자 잘 따라오시길 바랍니다!!

textField 의 제한 거는 코드를 검색하면 일반적으로 나오는 코드가 shouldChangeCharactersIn 메소드를 사용하는 겁니다 (텍스트필드에 뭔가 타이핑이 되면 실행되는 메소드) 
일반적으로 나오는 이유는 영어권에서 저걸 사용해도 아무런 문제가 없기 떄문입니다. 그러나 우리 한글에는 받침이 있어서 문제가 생깁니다. 

한글이라서 생기는 텍스트 필드의 문제를 살펴봅시다!
(제한은 5글자라고 예시듭시다)
1. 가나다라마 / 원래 치고 싶은건 가나다라맘 이었지만 텍스트 필드는 ㅁ(받침)을 인식하지 못해서 shouldChangeCharactersIn ~메소드를 썼을때 5글자가 됐다고 판단해서 더 이상 입력받지 못하게 해버립니다. 그래서 이런 문제가 발생합니다!
그래서 우리는 shouldChangeCharactersIn 를 사용할 수 없고 textFieldDidChangeSelection 를 사용해서 변화가 있을때 실행하는 메소드를 사용합니다.

textFieldDidChangeSelection 를 사용하면서 5글자 이후에 받아오는것은 버리고 딱 내가 원하는 5글자만 보여주면 되지 않을까? 라는 생각에서 시작된 코드입니다.

가나다라마 라면 startIndex는 가 0이고 endIndex는 5입니다. (let endIndex = text.index(text.startIndex, offsetBy: maxLength))
<img width="961" alt="스크린샷 2022-10-19 오전 1 19 55" src="https://user-images.githubusercontent.com/59243274/196486979-07c4f3ec-0418-4e60-950e-2ee9d2b4b8f5.png">

<img width="927" alt="스크린샷 2022-10-19 오전 1 22 10" src="https://user-images.githubusercontent.com/59243274/196487462-57248479-f49a-42ff-84ad-0d18f8667321.png">

그러면 fixedText는 0에서 ..<는 미만이니까 5미만 0,1,2,3,4까지 받아오니까 "가나다라마"가 되겠죠? 

그것을 이제 textField.text 로 넣어주면 우리가 제한한 것 만큼만 보이도록 하는겁니다. 

그런데 여기서 또 문제가 발생합니다.
텍스트 필드의 입력위치가 계속 5번째에 있기때문에 가나다라마 후에 바를 입력하면 가나다라바 가 되는것입니다. 마지막위치에서 계속 값을 변경하게 되고 백스페이스를 누를시 지금까지 쌓인 글자가 이상하게 막 등장하는 버그가 발생합니다. 

그래서 꼼수처럼 " " 공백을 줘버리는겁니다! 
그러면 textField에는 가나다라마( ) 까지 있는거처럼하고 입력위치를 6번째로 옮겨버리는것입니다!

2022-10-18 23:24 UTC, MMMIIIN commented on Maddori.Apple/Maddori.Apple/Global/Base/BaseViewController.swift
> +        hideKeyboardWhenTappedAround()
최고의 토마토 !

2022-10-18 23:49 UTC, MMMIIIN commented on Maddori.Apple/Maddori.Apple/Global/UIComponent/KigoTextField.swift
> +        self.autocapitalizationType = .none
p1; 

시뮬돌려보니 textField가 각지게 나오는데, 
여기 conerRadius가 안잡혀있는 것 같습니다 !

2022-10-18 23:57 UTC, MMMIIIN commented on Maddori.Apple/Maddori.Apple/Global/UIComponent/KigoTextField.swift
> +        self.leftViewMode = .always
p4;

요 함수 제 PR에서 extension으로 만들어 뒀는데 어떻게 하는게 좋을까요 ??

2022-10-19 00:09 UTC, MMMIIIN commented on Maddori.Apple/Maddori.Apple/Screen/Signup/SignupViewController.swift
> +    // MARK: - life cycle
한 칸 못참지...

2022-10-19 00:12 UTC, MMMIIIN commented on Maddori.Apple/Maddori.Apple/Screen/Signup/SignupViewController.swift
> +        render()
p3;

configUI와 render는 굳이 적어주지 않아도 됩니다..람쥐

2022-10-19 00:17 UTC, MMMIIIN commented on Maddori.Apple/Maddori.Apple/Screen/Signup/SignupViewController.swift
> +            $0.bottom.equalTo(view.safeAreaLayoutGuide)
p3;

bottom이 피그마에선 2정도 띄어져있는데, 확인 부탁드립니다 !

2022-10-19 01:30 UTC, Guel-git commented on Maddori.Apple/Maddori.Apple/Screen/Signup/SignupViewController.swift
> +                textField.text = fixedText + " "
와우 설명 완전 명쾌해요 ㅋㅋㅋ 최고의 선생님... 이 글은 진짜 자산이네요,,,, 👍

2022-10-19 01:42 UTC, MMMIIIN commented
테스트 방법에 SceneDelegate 수정하는 코드도 올려주시면 좋을 것 같습니다 ^_______^

2022-10-19 02:05 UTC, dangsal commented on Maddori.Apple/Maddori.Apple/Screen/Signup/SignupViewController.swift
> +            $0.bottom.equalTo(view.safeAreaLayoutGuide)
수정 완료입니다! 그런데 제가 어제 피그마에 값을 다 봤는데 여러개가 틀린거 보면 제가 칠칠치못한걸까요.. 분명히 확인 다 헀는데 값이 몇개가 이상하네유 ㅠ.ㅠ. 주의하겠습니당 수정완료옴

2022-10-19 02:10 UTC, dangsal commented on Maddori.Apple/Maddori.Apple/Screen/Signup/SignupViewController.swift
> +                self.doneButton.transform = CGAffineTransform(translationX: 0, y: -keyboardSize.height + 30)
![Simulator Screen Shot - iPhone 14 Pro - 2022-10-19 at 11 06 29](https://user-images.githubusercontent.com/59243274/196580776-9ae2fd0e-e4ac-4eb9-ad35-d6400b32d4f1.png)
 
오똔가요?

2022-10-19 02:28 UTC, hwiwonK approved these changes
수고 많으셨습니다! 코드가 정말 깔끔해서 나중에 구현할 때 많은 도움이 될 것 같아요👍

2022-10-19 02:28 UTC, hwiwonK commented on Maddori.Apple/Maddori.Apple/Screen/Signup/SignupViewController.swift
> +                    self.setCounter(count: textField.text?.count ?? 0)
p5;
텍스트 필드 수정이 일어날 때마다 setCounter가 수행되게 textFieldDidChangeSelection 내에서 구현이 되어있어서, 여기서 또 setCounter를 수행하면 같은 함수가 반복 수행되는 것 같습니다!
setCounter 코드 부분 지우고 실행 돌려봤는데 문제 없이 돌아가서, 이 부분은 삭제해도 괜찮을 것 같아 코멘트 남깁니다. 따로 이렇게 구현하신 이유가 있으시면 어떤 이유인지 궁금합니다🧐

2022-10-19 02:36 UTC, seongmin221 requested changes
대박적 대박적 고생 많으셨습니다!! ㅎ

2022-10-19 02:36 UTC, seongmin221 commented on Maddori.Apple/Maddori.Apple/Global/Literal/SizeLiteral.swift
> +    static let topPadding: CGFloat = 20
p1;
요걸 10/19 아침 데일리 스크럼에서 조정하기로 한거죠?!?!?
피그마랑 시뮬이랑 8 차이 나서 12로 줄여주면 좋겠습니다!

2022-10-19 02:36 UTC, seongmin221 commented on Maddori.Apple/Maddori.Apple/Screen/Signup/SignupViewController.swift
> +                textField.text = fixedText + " "
와우.. 요런거 어디 저장해둘 곳 없나요..

2022-10-19 02:37 UTC, seongmin221 commented on Maddori.Apple/Maddori.Apple/Global/Literal/SizeLiteral.swift
> +    static let topPadding: CGFloat = 20
아악 요게 나중에 사용할 사람 있으면 그 사람이 고치기로 했죠?!?! 깜빡했네요 ㅎ approve로 바꿔야겠슴다

2022-10-19 02:37 UTC, seongmin221 approved these changes

2022-10-19 03:09 UTC, Guel-git commented on Maddori.Apple/Maddori.Apple/Screen/Signup/SignupViewController.swift
> +                self.doneButton.transform = CGAffineTransform(translationX: 0, y: -keyboardSize.height + 30)
최고의 선생님 !

2022-10-19 03:09 UTC, dangsal commented on Maddori.Apple/Maddori.Apple/Screen/Signup/SignupViewController.swift
> +                    self.setCounter(count: textField.text?.count ?? 0)
생각해보니까 메리 의견이 맞는거같아요!!! 수정하겠습니다 ㅎㅎ 감사합니다

2022-10-19 03:10 UTC, Guel-git commented on Maddori.Apple/Maddori.Apple/Global/Literal/SizeLiteral.swift
> +    static let topPadding: CGFloat = 20
저는 제 브랜치에서 12로 바꿔두었어요!

2022-10-19 03:11 UTC, dangsal commented on Maddori.Apple/Maddori.Apple/Global/Literal/SizeLiteral.swift
> +    static let topPadding: CGFloat = 20
수정하겠습니다!

2022-10-19 05:52 UTC, MMMIIIN approved these changes
멋져멋져 !

2022-10-19 08:42 UTC, merged