[ADD] 피드백 추가하기_멤버 선택 뷰 구현
DeveloperAcademy-POSTECH/MacC-Team-Maddori.Apple pull request #17
Opened 2022-10-19 03:32 UTC by Guel-git

## 🌁 Background
피드백 추가하기 모달에서 멤버를 선택하는 뷰를 구현했습니다

## 👩‍💻 Contents
[추가된 파일 & 내용]
- Screens/AddFeedBack/AddFeedBackMember/AddFeedBackMemberViewController
- Extension/UILabel+Extension : setLineSpacing() - 띄어쓰기가 있는 텍스트의 줄 간격 조정을 위한 함수
- Global/UIComponent/MemberCollectionView : 멤버 목록 뷰
- Global/UIComponent/MemberCollectionViewCell : 멤버 라벨 

## ✅ Testing
feature/12-add-feedback-member 브랜치로 이동하셔서 root view를 AddFeedbackMemberViewController 로 바꿔주세요 !

## 📱 Screenshot
<img src="https://user-images.githubusercontent.com/81340603/196588885-286140b6-a568-4dc4-8a4e-3ae74cc7fa1d.png" width=150 />

## 📝 Review Note
1. CornerRadius 가 있는 View 또는 Label 뒤에 그림자를 넣는 문제
- CornerRadius는 masksToBounds = true 인 경우에만 작동을 하는데 masksToBounds 가 true이면 자신의 view bounds 경계에 있는 영역만 보여주기 때문에 그 영역을 넘어서는 그림자를 넣을 수 없게 됩니다. 그래서 뒤에 CALayer로 그림자를 주고 그 레이어를 view에 올리고 마지막으로 member label을 view에 올려서 그림자를 구현했습니다. 그림자를 넣는 코드가 좀 길어서 다음 배포 때는 extension으로 뺄 생각입니다 (노션에 있는 dev 폴더에 '다음 개발 목록' 페이지를 추가했습니다) 지금 코드가 좋은 건지 잘 모르겠어서 더 좋은 방법이 있다면 공유 부탁드려요!
2. 띄어쓰기가 있는 라벨의 줄간격
- 띄어쓰기가 있는 라벨 (title)은 줄 사이에 10px 간격이 필요합니다. 이는 lineHeight와 다른 lineSpacing으로 구현할 수 있는데 10px으로 간격을 주면 피그마보다 간격이 6px 정도 커져서 10보다 6 작은 4px로 지정해두었습니다. 띄어쓰기가 있는 게 각 뷰의 title 뿐이라 모두 동일한 줄간격을 가지고 있습니다. 때문에 extension을 쓸 때 따로 파라미터로 넘겨줄 필요가 없어서 extension에 값을 지정해두었습니다. title에 사용이 필요할 경우 label.setLineSpacing()으로 바로 사용하시면 됩니다!
3. 그림자 shadowRadius
- 피그마 상으로는 blur 가 4라서 shadowRadius에도 그대로 적용해봤더니 피그마보다 shadow가 넓게 표시되더라구요.. 일단 눈대중으로 4가 아닌 2로 맞춰 두었습니다!

## 📣 Related Issue
- close #12 

## 📬 Reference
https://boidevelop.tistory.com/m/87
https://babbab2.tistory.com/m/41

2022-10-19 05:57 UTC, dangsal commented on Maddori.Apple/Maddori.Apple/Global/Literal/ImageLiteral.swift
> +    // MARK: - navigation
p5;

이미지 리터럴에서는 저는 아이콘인지, 이미지인지, 버튼인지를 mark로 나눴는데 그렇게 나누는건 어떠세요?

이유: 이미지 같은 경우는 많은 뷰컨에서 사용될 수 도 있어서 이 이미지의 용도를 변수명에서부터 알수 있게 
아이콘: icXmark 
버튼: btnXmark
이미지: imageXmark 
이런식으로 했었걸랑요~ 제안제안입니다!

2022-10-19 05:57 UTC, dangsal commented on Maddori.Apple/Maddori.Apple/Global/Literal/SizeLiteral.swift
> +    static let topPadding: CGFloat = 12
저랑 컨플릭트 나면 구냥 아무거나 지우죵!

2022-10-19 06:00 UTC, dangsal commented on Maddori.Apple/Maddori.Apple/Global/UIComponent/ExitButton.swift
> +        self.frame = CGRect(x: 0, y: 0, width: 44, height: 44)
p1;

프레임에 44,44 를 주지 않아도 똑같이 작동을 합니다! 그래서 지워주셔도 된다는점~~

이유: ios에서 레이아웃을 잡는 방법은 3가지가 있어요
1. frame 기반으로 잡기
2. autoLayout으로 잡기
3. autoResizing 으로 잡기

프레임으로 프레임을 44.44 로 잡아도 저희는레이아웃을 잡아줄때 결국 오토레이아웃 기반으로 잡기 때문에 또 44,44값을 줘야합니다! 그래서 필요가 없어요~~

2022-10-19 06:02 UTC, dangsal commented on Maddori.Apple/Maddori.Apple/Global/UIComponent/ExitButton.swift
> +        self.frame = CGRect(x: 0, y: 0, width: 44, height: 44)
그런데 이 버튼은 오토레이아웃으로 잡지 않는군요!!! 

그렇다면 필요한 코드 같아요!!

2022-10-19 06:06 UTC, dangsal commented on Maddori.Apple/Maddori.Apple/Global/UIComponent/MemberCollectionView.swift
> +        static let collectionVerticalSpacing: CGFloat = 40
p4;

저는 이 부분의 코드를 조심스레 변경하는거에 대해 의견 내봅니다!
패딩값을 제외한 38-24 = 14 해서 14와 16으로 하는걸로요!

이유: 컬렉션뷰가 사실 패딩값만큼 뺴고 오토레이아웃을 잡는거랑 지금 당장은 다른게 없지만, 나중에 패딩값이 바뀌는 상황이 오면 이부분은 기억했다가 다시와서 바꿔야하는 소요가 든다고 생각해요!! 

그래서 아래에 render 부분이 컬렉션뷰에서 패딩값을 주고 여기서는 패딩값은 뺀부분부터 하면 어떨지 제안합니다!

2022-10-19 06:10 UTC, dangsal commented on Maddori.Apple/Maddori.Apple/Global/UIComponent/MemberCollectionView.swift
> +        static let cellWidth: CGFloat = UIScreen.main.bounds.width * 0.36
p5;

셀 너비는 비율로 주신 이유가 있을까요?? 

저는 이부분 같은 경우는 상수로 줘도 될거같다고 생각하거든요!

이유: 우리가 아이패드를 고려하는것도 아니고 해서 135로 줘도 되지 않을까..?하는 생각입니다

2022-10-19 06:11 UTC, dangsal commented on Maddori.Apple/Maddori.Apple/Global/UIComponent/MemberCollectionView.swift
> +//
그런데 이 컬렉션 뷰가 재사용이 되나요?? (제가 못찾았나해서..)

글로벌의 UIComponent 에 있는 이유가 혹시 있으실까요?
저는 AddFeedBackViewController 안에 UIComponent 그룹 만들어서 여기에 두시는게 맞다고 생각합니다!

2022-10-19 06:14 UTC, Guel-git commented on Maddori.Apple/Maddori.Apple/Global/UIComponent/MemberCollectionView.swift
> +//
아 회고 시간이 시작했을 때 회고 대상자를 선정하는 화면에서 사용됩니다 !

2022-10-19 06:18 UTC, Guel-git commented on Maddori.Apple/Maddori.Apple/Global/UIComponent/MemberCollectionView.swift
> +        static let cellWidth: CGFloat = UIScreen.main.bounds.width * 0.36
제가 생각하기에는 아이폰 미니보다 가로 디스플레이가 큰 경우 버튼을 기준으로 양옆 패딩이 커지는 것보다 버튼 자체의 width가 자연스럽게 커지는 게 더 자연스러울 거라고 생각했어요! 다른 분들의 의견이 궁금하네요! @MMMIIIN @seongmin221 @hwiwonK

2022-10-19 06:21 UTC, MMMIIIN commented on Maddori.Apple/Maddori.Apple/Global/Literal/ImageLiteral.swift
> +
p5;

요 부분이 제 pr이랑 겹치는 부분 같아서 한쪽이 먼저 머지되면 수정해야할 것 같습니다 ! 
(내가먼저 해야지)

2022-10-19 06:22 UTC, MMMIIIN commented on Maddori.Apple/Maddori.Apple/Global/Resource/Assets.xcassets/Navigation/exitButton.imageset/Contents.json
> +}
p3;

이게 SFSymbol에 있는 아이콘이 아니었나요 ??

2022-10-19 06:23 UTC, dangsal commented on Maddori.Apple/Maddori.Apple/Global/UIComponent/MemberCollectionView.swift
> +            bottom: collectionVerticalSpacing,
p5;

사실 이부분은 verticalSpacing이 아니여도 될거같은데 이 부분 혹시 사용법 아시나용???? 

저는 잘못알고있어서 최근에 다시 알게되었거든요 혹시나 해서 슬쩍 적어둘게요!!

<img width="600" alt="image" src="https://user-images.githubusercontent.com/59243274/196612629-d89f1c8f-d1a8-4dac-9426-ce4c41d8aa38.png">

2022-10-19 06:23 UTC, MMMIIIN commented on Maddori.Apple/Maddori.Apple/Global/UIComponent/ExitButton.swift
> +import SnapKit
p2;

그렇다면 요 import SnapKit은 필요가 없어 보입니다 !

2022-10-19 06:24 UTC, MMMIIIN commented on Maddori.Apple/Maddori.Apple/Global/UIComponent/ExitButton.swift
> +        self.frame = CGRect(x: 0, y: 0, width: 44, height: 44)
프레임을 이렇게 잡는 게 맞는방식 같아요 !
컴포넌트에서 크기에 관한 프레임을 다 설정해두고 사용하는 부분에선 위치만 잡아서 쓰는 방식이 맞는 것 같습니다 !
최고최고 !!

2022-10-19 06:28 UTC, MMMIIIN commented on Maddori.Apple/Maddori.Apple/Global/UIComponent/ExitButton.swift
> +    }
p3;

코드의 통일성을 위해 다른 view와 같이 처리하는게 어떨까.. 제안해봅니다.. ^_____^
스토리보드에 관한 init은 실행되지 않아서 그렇습니당..

```suggestion
    required init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
```

2022-10-19 06:36 UTC, dangsal commented on Maddori.Apple/Maddori.Apple/Global/UIComponent/MemberCollectionView.swift
> +        print(memberList[indexPath.item])
p1;

print문은 나중에 삭제할거라는 FIXME 요론고 하나만 부탁드려욤~

2022-10-19 06:37 UTC, dangsal commented on Maddori.Apple/Maddori.Apple/Global/UIComponent/MemberCollectionViewCell.swift
> +        static let frame = CGRect(x: 0, y: 0, width: Size.width, height: Size.height)
p1;

요고는 위에서 리뷰단거의 이유로 없애셔도 됩니다!

2022-10-19 06:40 UTC, dangsal commented on Maddori.Apple/Maddori.Apple/Global/UIComponent/MemberCollectionView.swift
> +        static let cellWidth: CGFloat = UIScreen.main.bounds.width * 0.36
그렇다면 약간 height 도 비율로 해야하지 않을까? 라는 생각입니다! 왜냐면 가로만 비율로 늘어나면... 으으 처럼 옆으로만 늘어난 느낌이 될거같아서요!!

2022-10-19 06:41 UTC, MMMIIIN commented on Maddori.Apple/Maddori.Apple/Global/UIComponent/MemberCollectionView.swift
> +//
음... 그러네요 그냥 viewController 자체를 분기처리하는게 나은 방법일 수 도 있겠다 생각이 드네요 ??
UI는 똑같고 1. 아래에 버튼이 있는지 없는지 차이 밖에 없는 것 같네요 ?? 닉네임을 클릭했을 때 view이동하는건 똑같을 것 같아서요 !

2022-10-19 06:45 UTC, MMMIIIN commented on Maddori.Apple/Maddori.Apple/Global/UIComponent/MemberCollectionView.swift
> +        static let collectionVerticalSpacing: CGFloat = 40
동의합니다 2222
피그마에서 컬렉션뷰에 대한 프레임이 안잡혀있고 내부 셀로 바로 디자인 되서 헷갈린 문제인 것 같아요 !
<img width="533" alt="image" src="https://user-images.githubusercontent.com/78677571/196616410-cc0a6f6b-030f-4212-81fb-b296c4a14daa.png">

피그마에서 셀들을 품고있는 프레임을 하나 만들어서 전체 패딩을 컬렉션뷰에 주고, 내부 셀들의 위치를 잡아야할 듯 합니다 !

2022-10-19 06:50 UTC, MMMIIIN commented on Maddori.Apple/Maddori.Apple/Global/UIComponent/MemberCollectionView.swift
> +        static let cellWidth: CGFloat = UIScreen.main.bounds.width * 0.36
이건 저도 예전부터 고민했던 문젠데 정답을 잘 모르겠어요..
아이패드를 고려안한다곤 하지만 사실 그건 저희 한정이고, 실제 앱들에선 아이패드도 다 지원하는데 거기의 방식이 아이패드인지 판단해서 그에 걸맞는 상수를 주는 것인지, 진저의 코드처럼 비율로 줘서 flexible하게 처리를 하는건지는 잘 모르겠네요 ..

근데 비율로 처리해서 특이한 상황에서 cell의 크기가 커졌다 해도, 다른 텍스트값들은 변하지 않기 때문에 여기선 상수로 처리하는게 맞는 것 같습니다 ! flexible하게 처리하려면 모든 UI요소들을 다 동일하게 처리하는게 맞는 것 같다고 문득 생각이 들었습니다 !

2022-10-19 06:51 UTC, dangsal commented
그냥 생각에는 
<img width="800" alt="스크린샷 2022-10-19 오후 3 50 47" src="https://user-images.githubusercontent.com/59243274/196617474-41e9c45f-91fe-4978-be3c-23f1b8f8a69e.png">
요론식으로 하면 되지 않을까? 생각이 드는데 혹시 이 방법해보셨나요?? 그림자 관련!!

2022-10-19 07:46 UTC, MMMIIIN commented on Maddori.Apple/Maddori.Apple/Global/UIComponent/MemberCollectionView.swift
> +            bottom: collectionVerticalSpacing,
아까 얘기한 방법으로 수정하면 좋을 듯 합니다 !

2022-10-19 07:50 UTC, MMMIIIN commented on Maddori.Apple/Maddori.Apple/Global/UIComponent/MemberCollectionViewCell.swift
> +        view.clipsToBounds = false
p3;

default값이 false인데 따로 선언하신 이유가 있을까요오오오??

2022-10-20 00:10 UTC, seongmin221 requested changes
고생 많으셨습니다!!
다들 빠르시군요.. 저도 빨리 하고 올려야겠네요 ㅎ

2022-10-20 00:40 UTC, hwiwonK commented on Maddori.Apple/Maddori.Apple/Global/UIComponent/MemberCollectionView.swift
> +        static let cellWidth: CGFloat = UIScreen.main.bounds.width * 0.36
저도 일단은 상수로 다 구현하는게 좋습니다! 가로 디스플레이가 큰 경우를 고려하면 이 부분 뿐만 아니라 텍스트 줄 수 등도 다 변경해야할 것 같아서, 아이패드 등에 맞춘 설정 변경은 나중에 한 번에 하는게 맞을 것 같아요!

2022-10-20 01:12 UTC, hwiwonK reviewed
수고 많으셨습니다! 컬렉션 뷰 나중에 구현할 일 있으면 참고할게요😄
다른 분들이 코멘트 남긴 부분 수정해주신거 확인되면 approve 할게요!

2022-10-21 01:37 UTC, Guel-git commented on Maddori.Apple/Maddori.Apple/Global/Extension/UILabel+Extension.swift
> +        }
앗 이건 띄어쓰기가 있는 Title 라벨에서 사용되는 line spacing입니다! 적용되는 곳이 Title 뿐이라서 extension에 상수값으로 지정해두었고 피그마 상으로는 10인데 10으로 적용하면 실제보다 커서 4로 주었습니다!

2022-10-21 01:38 UTC, Guel-git commented on Maddori.Apple/Maddori.Apple/Global/UIComponent/MemberCollectionViewCell.swift
> +        view.clipsToBounds = false
[e17af7e](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Maddori.Apple/pull/17/commits/e17af7e748038f5f3044c98787f00579b9070f5c)
제가 코드 작성할 때 헷갈리지 않도록 넣었습니다.. 다음부터는 빼겠습니다 !
그저께 호야랑 이드랑 논의했던 그림자 넣기 방식으로 코드 수정했습니다 !

2022-10-21 01:38 UTC, Guel-git commented on Maddori.Apple/Maddori.Apple/Global/UIComponent/MemberCollectionView.swift
> +        print(memberList[indexPath.item])
[e17af7e](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Maddori.Apple/pull/17/commits/e17af7e748038f5f3044c98787f00579b9070f5c)
수정해서 반영했습니다 ! 감사합니다 ㅎㅎ

2022-10-21 01:39 UTC, Guel-git commented on Maddori.Apple/Maddori.Apple/Global/UIComponent/ExitButton.swift
> +    }
수정해서 반영했습니다! 감사합니다 :)

2022-10-21 01:39 UTC, Guel-git commented on Maddori.Apple/Maddori.Apple/Global/UIComponent/ExitButton.swift
> +import SnapKit
[e17af7e](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Maddori.Apple/pull/17/commits/e17af7e748038f5f3044c98787f00579b9070f5c)
스냅킷 넣는 게 습관이 되었네요.. 매의 눈 감사합니다 !

2022-10-21 01:40 UTC, Guel-git commented on Maddori.Apple/Maddori.Apple/Global/UIComponent/MemberCollectionView.swift
> +            bottom: collectionVerticalSpacing,
[e17af7e](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Maddori.Apple/pull/17/commits/e17af7e748038f5f3044c98787f00579b9070f5c)
수정해서 반영해두었습니다 !

2022-10-21 01:41 UTC, Guel-git commented on Maddori.Apple/Maddori.Apple/Global/Resource/Assets.xcassets/Navigation/exitButton.imageset/Contents.json
> +}
[e17af7e](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Maddori.Apple/pull/17/commits/e17af7e748038f5f3044c98787f00579b9070f5c)
악.. 아주 까먹었어요.. 열심히 pdf 로 변환해서 넣었는데..ㅋㅋㅋㅋ
수정해서 반영해두었습니다 :)

2022-10-21 01:42 UTC, Guel-git commented on Maddori.Apple/Maddori.Apple/Global/UIComponent/MemberCollectionView.swift
> +        static let cellWidth: CGFloat = UIScreen.main.bounds.width * 0.36
[e17af7e](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Maddori.Apple/pull/17/commits/e17af7e748038f5f3044c98787f00579b9070f5c)
여러분들의 열정적인 코드리뷰 감동입니다... 저도 지금 단계에서는 비율로 주는 건 살짝 오바인 것 같네요 ㅋㅋㅋ 수정해서 반영해두었습니다!

2022-10-21 01:42 UTC, Guel-git commented on Maddori.Apple/Maddori.Apple/Global/UIComponent/MemberCollectionView.swift
> +        static let collectionVerticalSpacing: CGFloat = 40
[e17af7e](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Maddori.Apple/pull/17/commits/e17af7e748038f5f3044c98787f00579b9070f5c)
최고의 선생님! 수정해서 반영해두었습니다!

2022-10-21 01:43 UTC, Guel-git commented on Maddori.Apple/Maddori.Apple/Global/Literal/ImageLiteral.swift
> +    // MARK: - navigation
[e17af7e](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Maddori.Apple/pull/17/commits/e17af7e748038f5f3044c98787f00579b9070f5c)
오호라~ 수정해서 반영해두었습니다 !

2022-10-21 05:41 UTC, seongmin221 commented on Maddori.Apple/Maddori.Apple/Global/Extension/UILabel+Extension.swift
> +        }
엇 그.. 코드상에 줄 간격..ㅋㅋㅋㅋ cmd + i 의미였어욬ㅋㅋㅎ

2022-10-21 05:43 UTC, seongmin221 approved these changes
좋습니다좋습니다~!

2022-10-21 05:55 UTC, MMMIIIN commented on Maddori.Apple/Maddori.Apple/Global/Resource/Assets.xcassets/Navigation/exitButton.imageset/Contents.json
> +}
p2;

요건 삭제해도 괜찮은거 아닌가요오오오???

2022-10-21 05:58 UTC, Guel-git commented on Maddori.Apple/Maddori.Apple/Global/Resource/Assets.xcassets/Navigation/exitButton.imageset/Contents.json
> +}
악

2022-10-21 06:08 UTC, Guel-git commented on Maddori.Apple/Maddori.Apple/Global/Resource/Assets.xcassets/Navigation/exitButton.imageset/Contents.json
> +}
[f4a4425](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Maddori.Apple/pull/17/commits/f4a4425432258b77b36e1ac0021bdbb4f0981c63)
수정해서 반영해두었습니다! 역시 매의 눈 ..!

2022-10-21 06:08 UTC, Guel-git commented on Maddori.Apple/Maddori.Apple/Global/Extension/UILabel+Extension.swift
> +        }
[f4a4425](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Maddori.Apple/pull/17/commits/f4a4425432258b77b36e1ac0021bdbb4f0981c63)
악 수정해서 반영해두었습니다! 감사합니다 :)

2022-10-21 06:41 UTC, MMMIIIN approved these changes
수고하셨습니다
최고십니다 건강이슈 해결 잘 하십셔...
^_______^

2022-10-21 08:19 UTC, merged