[SETTING] 초기 프로젝트 세팅과 메인버튼을 추가했습니다.
DeveloperAcademy-POSTECH/MacC-Team-Maddori.Apple pull request #3
Opened 2022-10-14 13:25 UTC by MMMIIIN

## 🌁 Background

원활한 프로젝트 진행을 위해 초기 프로젝트 세팅을 했습니다. 

## 👩‍💻 Contents

- 폴더 구조를 정해뒀고, 자주 사용하는 Extension들을 추가해뒀습니다.
- 스토리보드를 삭제하고 SceneDelegate로 view를 연결했습니다.
- SnapKit 라이브러리를 추가했습니다.
- 메인 버튼을 추가했습니다.

설명이 필요하다 싶은 코드 부분에 어떤 코드인지 설명 적어두도록 하겠습니다 ^_________^

### Model 폴더 2개로 분리 이유
<img width="213" alt="image" src="https://user-images.githubusercontent.com/78677571/195855192-8a7543dd-6d30-463d-a12a-7501726f4fb6.png">

위와 같이 Model에서 두가지 폴더로 나눈 이유는 서버에서 API를 받는 response 폴더와, 클라에서 서버로 올릴 때 필요한 request body들을 담기위한 DTO를 분리하기 위함입니다

DTO에 대해 추가설명을 하자면
(서버쪽에서 DTO란 개념을 많이 사용하는데, 클라쪽에서도 필요하다고 생각합니다)
<img width="301" alt="image" src="https://user-images.githubusercontent.com/78677571/195855645-9e6fcdfe-4448-49a4-b935-4fa50b9890fd.png">
위와 같이 서버로 보내야하는 JSON 형식의 값들이 있다고 해보겠습니다 그럼 클라쪽에선 해당값들이 들어있는 struct를 만들어서 인코딩하게 됩니다. 그 과정에서 실제 view에 들어가는 model형식과, request를 보내야하는 model의 형식이 절대 같다는 보장이 없기 때문에 인코딩 전용 struct를 만들어서 명확하게 하기 위함입니다.
```swift
struct CreateRoomDTO: Encodable {
    var room: RoomDTO
    var member: MemberDTO
}

struct RoomDTO: Encodable {
    let title: String
    let capacity: Int
    let startDate: String
    let endDate: String
}

struct MemberDTO: Encodable {
    var colorIdx: Int
}
```
위와같이 해당 값들에 대한 명확한 struct를 DTO라 생각하시면 됩니다.

## ✅ Testing

해당 브랜치로 이동 후 돌려보시면 됩니다 ^______^ 
MainViewController에 어떤식으로 코드가 작성될지 예시느낌으로 적어뒀습니다.

## 📱 Screenshot

<img width="375" alt="image" src="https://user-images.githubusercontent.com/78677571/195853197-a6f5945d-f0fa-4189-9a5d-94bab24652a9.png">

## 📝 Review Note

아까 MVC에 대해서 얘기하고 폴더구조가 달라질 수도 있다 말씀드렸는데, 현재 제가 실수하고 있던 MVC는 ViewController 내부에 Model에 관한 로직이 다 들어가있던 문제였습니다. 그로인해 ViewController가 굉장히 Massive한 ViewController가 되었습니다. 그래서 이번엔 각 ViewController에 사용되는 Model들을 Network/Request 내부에 작성하고 그 Model 파일 내부에서 계산 로직들을 처리후 리턴하는 방식을 사용하려 합니다. 

현재는 위의 말이 이해가 안되더라도 개발이 진행됬을 때 코드리뷰를 통해 어떤 문제가 있고, 어떻게 개선하면 좋을지 코멘트 남기도록 하겠습니다.

## 📣 Related Issue

- close #2 

## 📬 Reference

https://github.com/DeveloperAcademy-POSTECH/MC2-Team5-Firefighter/

2022-10-14 13:29 UTC, MMMIIIN commented on Maddori.Apple/Maddori.Apple/Global/Extension/NSObject+Extension.swift
> +}
TableViewCell, CollectionViewCell을 register할 때 forCellWithReuseIdentifier 값을 해당 className으로 사용하기 위한 코드입니다.

2022-10-14 13:33 UTC, MMMIIIN commented on Maddori.Apple/Maddori.Apple/Global/Extension/UIButton+Extension.swift
> +    }
MainButton에서 활성화 상태와, 비활성화 상태에 따른 backgroundColor를 설정하려면 
<img width="618" alt="image" src="https://user-images.githubusercontent.com/78677571/195859352-8ddfc60f-a6d2-4338-b0d7-bbb6b5baab79.png">
위와 같이 UIImage를 설정해야하는데,
이 함수를 통해 UIColor 값으로 UIImage를 만들고 backgroundColor도 설정해주는 코드입니다 ^_______^

2022-10-14 13:34 UTC, MMMIIIN commented on Maddori.Apple/Maddori.Apple/Global/Extension/UICollectionView+Extension.swift
> +    }
Hi-Fi가 완성되고 collectionView에 header나 footer가 필요없으면 삭제하겠습니다.

2022-10-14 13:35 UTC, MMMIIIN commented on Maddori.Apple/Maddori.Apple/Global/Extension/UIColor+Extension.swift
> +    }
hex값으로 Color를 뽑아내는 코드입니다

2022-10-14 13:35 UTC, MMMIIIN commented on Maddori.Apple/Maddori.Apple/Global/Extension/UIFont+Extension.swift
> +    case bold = "AppleSDGothicNeo-Bold"
여기도 Hi-Fi가 완성되고 필요하지 않은 폰트들은 삭제하도록 하겠습니다

2022-10-17 06:01 UTC, dangsal commented on Maddori.Apple/Maddori.Apple/Global/Base/BaseViewController.swift
> +    }
p5;

요 코드 설명 한번만 부탁드려욤

2022-10-17 06:15 UTC, dangsal commented on Maddori.Apple/Maddori.Apple/Global/Extension/UITableView+Extension.swift
> +    }
p2; 

저는 이 코드에 대한 사용처를 잘 모르겠습니당!!

2022-10-17 06:16 UTC, MMMIIIN commented on Maddori.Apple/Maddori.Apple/Global/Base/BaseViewController.swift
> +    }
애니또 하면서 뒤로가기 제스처가 무분별하기 먹히는 문제가 있었는데, 그 문제를 해결하기 위해 듀나가 작성했던 코드였습니다. 네비게이션 스택에 1개 이상일 때부터 드래그하는 제스쳐가 적용되도록 하는 코드입니다 !

https://velog.io/@tmdckd232/UIKit-%EB%93%9C%EB%9E%98%EA%B7%B8%EB%A1%9C-%ED%8E%98%EC%9D%B4%EC%A7%80-%EB%92%A4%EB%A1%9C%EA%B0%80%EA%B8%B0

2022-10-17 06:18 UTC, dangsal reviewed
메인 버튼의 자세한 변경은 나중에 다시 하는걸로 합시다!! 고생하셨습니다!!! 

케미 짱짱

2022-10-17 06:18 UTC, MMMIIIN commented on Maddori.Apple/Maddori.Apple/Global/Extension/UITableView+Extension.swift
> +    }
동의합니다 !
최대한 위와 같은 extension들을 사용안해보고 불편함을 느낀다면 그 때 추가해보도록 합시다 ^______^
감사합니다 !

2022-10-17 07:51 UTC, Guel-git commented on Maddori.Apple/Maddori.Apple/Global/Supports/SceneDelegate.swift
> +        window?.rootViewController = rootViewControoler
```suggestion
        let rootViewController = UINavigationController(rootViewController: MainViewController())
        window?.rootViewController = rootViewController
```
p1;
오타 수정 부탁드립니다!

2022-10-17 07:57 UTC, MMMIIIN commented on Maddori.Apple/Maddori.Apple/Global/Supports/SceneDelegate.swift
> +        window?.rootViewController = rootViewControoler
대박 매의눈.. 감사합니다 ^______^

[985985c](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Maddori.Apple/pull/3/commits/985985cf743bdf8fa41181f323fab2a10a3cda15)

2022-10-17 08:02 UTC, Guel-git commented on Maddori.Apple/Maddori.Apple/Global/Literal/TextLiteral.swift
> +    static let mainViewControllerTitle = "예시입니다...람쥐"
p6;
ㅋㅋㅋㅋ

2022-10-17 08:07 UTC, Guel-git commented
와우! 고생 많으셨습니다~ 덕분에 필요한 extension들 쏙쏙 뽑아서 사용할 수 있겠네요 !!!!

한 가지 궁금한 게,
Model/Request는 기존 ViewController에서 사용했던 Model 파트를 분리하기 위한 파일이고, Model/Response는 서버로부터 받은 내용을 View에 표시하기 전에 클라 쪽 Model 구조에 맞게 전처리하는 용도라고 생각하면 될까요?

2022-10-17 08:07 UTC, Guel-git submitted a review, later dismissed

2022-10-17 08:14 UTC, MMMIIIN commented
> 와우! 고생 많으셨습니다~ 덕분에 필요한 extension들 쏙쏙 뽑아서 사용할 수 있겠네요 !!!!
> 
> 한 가지 궁금한 게, Model/Request는 기존 ViewController에서 사용했던 Model 파트를 분리하기 위한 파일이고, Model/Response는 서버로부터 받은 내용을 View에 표시하기 전에 클라 쪽 Model 구조에 맞게 전처리하는 용도라고 생각하면 될까요?

response의 용도는 설명해주신 내용이 맞는데 request의 용도는 어떤 의미인지 잘 모르겠네요..?? request로 분리한 이유는 api body에 필요한 데이터 형식에 딱 맞는 struct를 생성하기위한 **데이터 전달용** 입니다

2022-10-17 08:15 UTC, MMMIIIN commented on Maddori.Apple/Maddori.Apple/Global/Literal/TextLiteral.swift
> +    static let mainViewControllerTitle = "예시입니다...람쥐"
이스터에그 발견을 축하드립니다

2022-10-17 08:19 UTC, Guel-git commented
> > 와우! 고생 많으셨습니다~ 덕분에 필요한 extension들 쏙쏙 뽑아서 사용할 수 있겠네요 !!!!
> > 한 가지 궁금한 게, Model/Request는 기존 ViewController에서 사용했던 Model 파트를 분리하기 위한 파일이고, Model/Response는 서버로부터 받은 내용을 View에 표시하기 전에 클라 쪽 Model 구조에 맞게 전처리하는 용도라고 생각하면 될까요?
> 
> response의 용도는 설명해주신 내용이 맞는데 request의 용도는 어떤 의미인지 잘 모르겠네요..?? request로 분리한 이유는 api body에 필요한 데이터 형식에 딱 맞는 struct를 생성하기위한 **데이터 전달용** 입니다

아 제가 하고 싶었던 말이에요! 이해됐습니다 :) 감사합니당!

2022-10-17 14:44 UTC, dangsal submitted a review, later dismissed
너무 고생하셨습니다!

2022-10-17 15:00 UTC, hwiwonK commented
수고 많으셨습니다! 설명이 너무 잘 되어있어서 이해가 잘 가요~!
덕분에 코딩이 훨씬 수월해지겠네요, 감사합니다 👍

2022-10-17 15:01 UTC, hwiwonK approved these changes

2022-10-17 23:44 UTC, seongmin221 commented on Maddori.Apple/Maddori.Apple/Global/Extension/UIButton+Extension.swift
> +    }
오.. 이런것도 있는지는 처음 알았네요
이 코드로 활성 비활성 모두 표현 가능하다는거죠??
대박..

2022-10-17 23:53 UTC, seongmin221 requested changes
후딱 봤어야 했는데 어쩌다보니 세션 직전인 지금 확인하네요😂
첫 세팅 고생 많으셨고 이제 하이파이 (거의)(왜 또 거의지..) 확정되었으니까
다같이 빡 코딩 시작해봅시다!!

2022-10-17 23:53 UTC, seongmin221 commented on Maddori.Apple/Maddori.Apple/Global/UIComponent/MainButton.swift
> +        static let height: CGFloat = 50
p1;
요놈이 하이파이에 mainbutton이 맞나요?
맞다면 height 사이즈 54로 늘렸습니다!!

2022-10-18 03:33 UTC, MMMIIIN commented on Maddori.Apple/Maddori.Apple/Global/UIComponent/MainButton.swift
> +        static let height: CGFloat = 50
수정했습니다 ^________^
[ea4ccc0](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Maddori.Apple/pull/3/commits/ea4ccc0411949b015e1be8454bd1b790d4483796)

2022-10-18 03:34 UTC, seongmin221 approved these changes
수고 많으셨습니다!!

2022-10-18 03:34 UTC, hwiwonK approved these changes
꼼꼼한 코드 리뷰 너무 좋습니다!
다들 수고 많으셨어요~👍

2022-10-18 03:35 UTC, dangsal approved these changes
참내

2022-10-18 03:35 UTC, Guel-git approved these changes
최고의 선생님 ! 🧪

2022-10-18 03:36 UTC, merged