[CHORE] 회고가 시작되었을 때 키워드가 없는 상황 추가
DeveloperAcademy-POSTECH/MacC-Team-Maddori.Apple pull request #372
Opened 2023-05-14 03:18 UTC by seongmin221

## 🌁 Background

현재 키워드가 없을 때 회고가 시작되어도 "첫 번째 키워드를 작성해주세요" 가 떠 있는데
UX 에 옳지 않다고 생각해서 텍스트를 바꾸도록 했습니다!

그냥 제가 임의로 "이번 회고에 작성된 키워드가 없습니다" 라고 해 뒀는데
제일 어려운 UX writing... 은 같이 생각해보아요 ㅠㅠ

## 📱 Screenshot

<img src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Maddori.Apple/assets/72431640/421775b5-2313-47df-98b2-b72cabd6ebfb" width="300">

## 👩‍💻 Contents

- textliteral 추가
- 회고가 시작되었을 때 피드백이 없다면 "이번 회고에 작성된 키워드가 없습니다" 추가

## ✅ Testing

키워드를 작성하지 않고 회고를 시작해보세용

## 📝 Review Note

## 📣 Related Issue

- close #371

## 📬 Reference

2023-05-14 09:46 UTC, Guel-git commented
이번 회고에는
작성된 피드백 키워드가
없습니다 🥲

는 어떤가요?

2023-05-15 03:38 UTC, seongmin221 commented
>

 
'피드백' 과 '키워드' 둘 중 하나만 적어도 된다고 생각하는데 어떤가욤..???
<img src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Maddori.Apple/assets/72431640/08d4cdda-bb20-451a-b2c1-19bef0e942f1" width="300">

진저 말대로 한거는 아래 !
<img src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Maddori.Apple/assets/72431640/8683a6a3-b306-4818-9da0-0ba32542ef11" width="300">

2023-05-15 05:52 UTC, dangsal commented
`이번` `회고에는` `작성된` `피드백이` `없습니다`.. ㅋㅋㅋㅋ 저는 요고요!

2023-05-15 14:19 UTC, seongmin221 commented
> `이번` `회고에는` `작성된` `피드백이` `없습니다`.. ㅋㅋㅋㅋ 저는 요고요!
![Simulator Screenshot - iPhone 14 Pro - 2023-05-15 at 23 19 22](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Maddori.Apple/assets/72431640/8e44a644-a0f8-46a9-9fd7-e82afaa5cdc0)

이모지... 를 넣을까 말까 했는데 없으니까 너무 딱딱한거 같더라구요 ㅠㅠ 일단 넣어봤는데 빼는게 좋을까유 ??

2023-05-15 14:20 UTC, dangsal commented
> > `이번` `회고에는` `작성된` `피드백이` `없습니다`.. ㅋㅋㅋㅋ 저는 요고요!
> 
> <img alt="" width="300" src="https://user-images.githubusercontent.com/72431640/238377642-8e44a644-a0f8-46a9-9fd7-e82afaa5cdc0.png">
> 이모지... 를 넣을까 말까 했는데 없으니까 너무 딱딱한거 같더라구요 ㅠㅠ 일단 넣어봤는데 빼는게 좋을까유 ??

ㅇ\아뇨 이모지 좋아요!!

2023-05-15 14:21 UTC, seongmin221 commented
괜찮다면 어프루브 ~

2023-05-15 14:31 UTC, dangsal approved these changes
오케이~ 저는 어푸르븐데 다른 분들 의견도 들어봐야할듯!

2023-05-17 06:01 UTC, MMMIIIN commented on Maddori.Apple/Maddori.Apple/Screen/Home/Home/HomeViewController.swift
> +                            self.emptyKeywordListWhenProgressing()
p1; 

현재 키워드가 없을때의 초기화 함수를 Progressing 단계에서 무조건 실행시켜 버리면 키워드가 있을때에도 빈 키워드가 뜨게 됩니다...
<img width="393" alt="image" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Maddori.Apple/assets/78677571/0e0bc3ae-942a-45cd-9057-f0be0f28a661">
위 사진과 같이 테스트용 키워드를 하나 추가해 뒀는데, 시작단계로 넘어가니까 
<img width="393" alt="image" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Maddori.Apple/assets/78677571/b2d471a8-c11f-4079-8b1c-51fe135038d1">
위와 같이 뜹니다...
키워드가 없을때 실행되는 조건으로 수정부탁드립니다!

2023-05-17 06:02 UTC, MMMIIIN requested changes
리뷰 확인 부탁드립니당~~

저도 UX Writing은 좋습니다 👍

2023-05-17 11:12 UTC, seongmin221 commented on Maddori.Apple/Maddori.Apple/Screen/Home/Home/HomeViewController.swift
> +                            self.emptyKeywordListWhenProgressing()
[edeb324](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Maddori.Apple/pull/372/commits/edeb324c9f0b2104a931eac230377c3375d30f93)
와우 대박적 실수했네욥 하하하하ㅏ핳ㅎ

2023-05-17 11:15 UTC, MMMIIIN approved these changes
수고하셨습니다~~
UX Writing까지 해주시고 아주 굿입니다 굿👍

2023-05-17 15:52 UTC, merged